export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const SET_SPINNER = "SET_SPINNER";
export const REMOVE_SPINNER = "REMOVE_SPINNER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";

export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const SET_MODAL = "SET_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";

export const APP_IS_ONLINE = "APP_IS_ONLINE"
export const APP_IS_OFFLINE = "APP_IS_OFFLINE"

export const SET_SLIDER = "SET_SLIDER"
export const REMOVE_SLIDER = "REMOVE_SLIDER"